### ISSUE TITLE
Fail to import phoenix.css

### ISSUE THREAD

**Issue by Neptius** [phoenixframework/tailwind#8]
Hello,

I created a simple demo project with the command "mix phx.new" then I followed the steps of intergration of tailwind but it seems that the application cannot import the "phoenix.css" file and its css:

![image](https://user-images.githubusercontent.com/16630174/147333161-e68e9016-dfa8-4afc-afda-657fad2b1772.png)

Maybe a configuration step is missing?
Thank.

**Comment by That-David-Guy** [comment]
Same, using a fairly clean build. The instructions to use this seem incomplete. I got the same error as above and none of the tailwind classes are working.

I'm assuming I need to import tailwind.css somewhere?

**Comment by Neptius** [comment]
Yeah, the documentation doesn't mention it but used the tailwind directives in "app.css" and it works.

```css
/* app.css */
@tailwind base;
@tailwind components;
@tailwind utilities;

/* ... */
```

But the import of css files doesn't work:

```css
/* This file is for your main application CSS */
@import "./phoenix.css";
```

**Comment by ben-maclaurin** [comment]
> Yeah, the documentation doesn't mention it but used the tailwind directives in "app.css" and it works.
> 
> ```css
> /* app.css */
> @tailwind base;
> @tailwind components;
> @tailwind utilities;
> 
> /* ... */
> ```
> 
> But the import of css files doesn't work:
> 
> ```css
> /* This file is for your main application CSS */
> @import "./phoenix.css";
> ```

I've opened a pull request for it #6

**Comment by ellismarkf** [comment]
I believe that this is happening because`esbuild` and `tailwind` are running in parallel. If you change the `tailwind` input option to take in the concatenated CSS file that `esbuild` produces, all the styles are there.

```elixir
config :tailwind,
  version: "3.0.7",
  default: [
    args: ~w(
      --config=tailwind.config.js
      --input=../priv/static/assets/app.css
      --output=../priv/static/assets/compiled.css
    ),
    cd: Path.expand("../assets", __DIR__)
  ]
```
It seems like `esbuild` needs to build the CSS file first, and _then_ `tailwind` can compile and inject the necessary additional classes.  Not sure if this is the expected behavior, but it's counter-intuitive.

**Comment by justlampin** [comment]
> But the import of css files doesn't work:
> 
> ```css
> /* This file is for your main application CSS */
> @import "./phoenix.css";
> ```

i believe this is because the standalone `tailwindcss` executable doesn't contain the [postcss-import](https://github.com/postcss/postcss-import) plugin. i believe it contains some tailwind-specific plugins and [autoprefixer](https://github.com/postcss/autoprefixer). it's partially noted here: https://github.com/phoenixframework/tailwind/blob/master/README.md?plain=1#L139-L141

iirc the default behavior of `@import` in stylesheets is to trigger an additional http request for the imported stylesheet (which is why you see the 404 in your network inspector), rather than inlining it. so you'd either need to revert back to non-standalone usage of `tailwind` (e.g. via `node`) so you can use the `postcss-import` plugin, or you'd need to configure your build tooling to copy the `@import`-ed stylesheet (`phoenix.css`) into your `/priv` directory for static assets, so that it's available to be served to the browser

**Comment by foucist** [comment]
If app.css is left alone, and a new input tailwind.css is added, then importing app.css works and you get phoenix.css as well:

```
       --input=../priv/static/assets/tailwind.css
       --output=../priv/static/assets/compiled.css
```

```
/* tailwind.css */
@import "app.css"

@tailwind base;
@tailwind components;
@tailwind utilities;
```
